### ISSUE TITLE
Linux support [feature-request]

### ISSUE THREAD

**Issue by cocowalla** [Giorgi/DuckDB.NET#1]
Hi, I'm interested in trying DuckDB from .NET, and naturally came across your bindings. I see support for Windows and MacOS already exist, and was wondering if you had plans to add Linux support?

**Comment by Giorgi** [comment]
Adding Linux support is as simple as making a copy of `NativeMethods.Windows.cs` class and replacing DllImports to use Linux library instead of dll file. I don't have a Linux environment set up so maybe you could send a PR?

**Comment by Giorgi** [comment]
Implemented in 605b8b809770738578d7fb8155c22ba21f1b99d3

**Comment by Giorgi** [comment]
@cocowalla Can you check 0.1.1 version of the library?
