### ISSUE TITLE
Concurent connections problems

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#10]
I am having problems with opening multiple connections at the same time. I get the DuckDB open failed error. 
Works fine when I take care to open connections one by one.
I think the design whereby a database object is created for the life of the process, and each connection open call takes this database object as a parameter is a simpler design to get right.
It is more in line with the way DuckDb thinks under the hood, and is not contrary to anything in the ado.net spec.

**Comment by Giorgi** [comment]
Can you share your code that results in the error?

**Comment by travis-leith** [comment]
I can put together a repro in F#. Would that be OK?

**Comment by Giorgi** [comment]
Yes

**Comment by travis-leith** [comment]
You can find the repro [here](https://github.com/travis-leith/duckdb_connections).
I have put together [3 test cases](https://github.com/travis-leith/duckdb_connections/blob/main/demo/Program.fs#L129).

If you run the project as is (setting VS to allow the exceptions) you will get a report of the test results.
in test1, everything is done sequentially. If you comment out test2 and test3, it runs fine.
in test2, queries are run concurrently.
in test3, connections are opened concurrently, then queries are run concurrently.

The test library I am using is called Expecto. Unless you tell it not to, it runs all tests concurrently.
If you leave all 3 tests, it fails. If you leave only test1, it succeeds.

**Comment by travis-leith** [comment]
Hmm, I just amended my test project with an implementation of the database dependency that makes sure connections are always opened sequentially by a single thread. The problem persists. So it is not about opening connections concurrently. It is actually about running queries concurrently.

**Comment by Giorgi** [comment]
@travis-leith Can you check if the [ThreadSafe-Connection-Open](https://github.com/Giorgi/DuckDB.NET/tree/ThreadSafe-Connection-Open) branch solves the problem for you?

**Comment by travis-leith** [comment]
I am getting the error: `System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

**Comment by Giorgi** [comment]
Fixed in #18
