### ISSUE TITLE
Catalog Error: Type with name __pivot_enum_0_0 does not exist creating a reader on a pivot

### ISSUE THREAD

**Issue by DanCory** [Giorgi/DuckDB.NET#110]
I don't have a narrow repro yet but the error message is:
Exception has occurred: CLR/DuckDB.NET.Data.DuckDBException
An unhandled exception of type 'DuckDB.NET.Data.DuckDBException' occurred in DuckDB.NET.Data.dll: 'Catalog Error: Type with name __pivot_enum_0_0 does not exist!
Did you mean "enum"?'
   at DuckDB.NET.Data.PreparedStatement.PrepareMultiple(DuckDBNativeConnection connection, String query)
   at DuckDB.NET.Data.DuckDbCommand.PrepareIfNeeded()
   at DuckDB.NET.Data.DuckDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at DuckDB.NET.Data.DuckDbCommand.ExecuteReader()

I've been unable to workaround this.

**Comment by Giorgi** [comment]
@DanCory Which NuGet package do you have installed and which version?

**Comment by DanCory** [comment]
DuckDB.NET.Data.Full 0.8.0

Pivot was only added in DuckDB 0.8.0

**Comment by DanCory** [comment]
I don't see a similar message using the DuckDB CLI and the same query.

**Comment by Giorgi** [comment]
Can you share demo database/script and a query that causes the error? Otherwise it will be hard to find the cause of the error.

**Comment by DanCory** [comment]
I built a narrow repro around the following code:
using DuckDB.NET.Data;
using DuckDBConnection duckDBConnection = new DuckDBConnection("Data Source=test");
duckDBConnection.Open();
DuckDbCommand command = duckDBConnection.CreateCommand();
command.CommandText="CREATE TABLE Cities(Country VARCHAR, Name VARCHAR, Year INT, Population INT);";
command.ExecuteNonQuery();
command.CommandText="PIVOT Cities ON Year USING SUM(Population);";
DuckDBDataReader reader = command.ExecuteReader();

Here's a full package, though I removed runtimes other than Win x64.
[pivot-bug.zip](https://github.com/Giorgi/DuckDB.NET/files/11583026/pivot-bug.zip)
This is using queries from https://duckdb.org/docs/sql/statements/pivot

**Comment by DanCory** [comment]
It looks like this error is coming from the DuckDB c++ code but I'm not sure how to get the call stack from there.

**Comment by Giorgi** [comment]
@DanCory Opened this issue in the DuckDB repo: https://github.com/duckdb/duckdb/issues/7720

**Comment by Giorgi** [comment]
This should be fixed in version 0.8.1-alpha.13 of https://github.com/Giorgi/DuckDB.NET/pkgs/nuget/DuckDB.NET.Data.Full

**Comment by DanCory** [comment]
With 0.8.1-alpha.13, I no longer get this error. But my original script is not completely working. I will file a new bug if needed.

**Comment by Seddryck** [comment]
I can confirm that with `0.8.0`, I had some issues probably related to the issue with extract_statement described at  https://github.com/duckdb/duckdb/issues/7720 but the version `0.8.1-alpha.19` works just fine.

**Comment by DanCory** [comment]
It appears that a single PIVOT statement now generates two result sets, the first of which has NoRows=true, the second has NoRows=false and the actual data. This is definitely implementation leaking out.

**Comment by Giorgi** [comment]
@DanCory This is because under the hood there are two queries and two results for a PIVOT statement. There will also be statements and two results if the `CommandText` is `Select * from table1; Select * from table2` and there is no way for the library to know which case is which. So it might be better to drop support for multiple select statements and implement that with `DbBatch`. In such cases the library would return only the last result for PIVOT queries. Any thoughts @Seddryck ?

**Comment by Seddryck** [comment]
I agree with your proposition, it sounds a smart way to move forward. Typically, the multiple result sets was the kind of "issue" that I met when I quickly tried to implement `DbBatch`.

**Comment by Giorgi** [comment]
@Seddryck Do you want to give it a try with these changes?

**Comment by Seddryck** [comment]
TBH, I fear that I don't know enough about the internals of DuckDB to be able to quickly conduct these changes and this week is already overbooked. Don't wait for me if I don't push anything tonight.

**Comment by Giorgi** [comment]
@DanCory The empty result issue is fixed in https://github.com/Giorgi/DuckDB.NET/tree/Pivot-Reader-Fix branch but it requires DuckDB version that's not released yet.
