### ISSUE TITLE
Consider changing DuckDBCommand.Prepare to noop instead of throwing NotSupportedException

### ISSUE THREAD

**Issue by roee88** [Giorgi/DuckDB.NET#118]
https://github.com/Giorgi/DuckDB.NET/blob/2cd0d80051db24500d57a273c5975f5ef6cb8f58/DuckDB.NET.Data/DuckDBCommand.cs#L108

When using abstractions like DbProviderFactory (or in the future DbDataSource) I think that it makes more sense to avoid throwing the exception here and allow it to pass through as a no operation. Otherwise, specialization for DuckDB commands is required.

**Comment by Giorgi** [comment]
@roee88 Can you send a PR?
