### ISSUE TITLE
Code from the example does not work

### ISSUE THREAD

**Issue by bykka** [Giorgi/DuckDB.NET#121]
I use the last DuckDB.NET.Bindings.Full version 0.8.1 and code from the example does not work because class DuckDBResult has only private properties

<img width="1523" alt="image" src="https://github.com/Giorgi/DuckDB.NET/assets/489997/06bf7e0b-f66b-4539-850a-6c8a762b540e">

**Comment by Giorgi** [comment]
Thanks for spotting the issue. The internal API has changed since I put those examples. Do you want to send a PR?

**Comment by bykka** [comment]
Take a look https://github.com/Giorgi/DuckDB.NET/pull/122

**Comment by Giorgi** [comment]
Thanks!
