### ISSUE TITLE
Parquet write fails with DuckDB.dll 0.2.8

### ISSUE THREAD

**Issue by mmauri** [Giorgi/DuckDB.NET#13]
Thanks for fixing the previous issue so quick.
I have tried to write a parquet file and it throws this error:
_**Catalog Error: Copy Function with name parquet does not exist!
Did you mean "csv"?**_

It works on the CLI duckdb.exe, I haven't found any doc stating that the C++ API does not  support Parquet, so I don't know if the issue is about your bindings or the Dll API itself.

```
using var conn = new DuckDBConnection("Data Source=:memory:");
try
{
    conn.Open();
    var command = conn.CreateCommand();

    command.CommandText = "CREATE TABLE integers(foo INTEGER, bar INTEGER);";
    var executeNonQuery = command.ExecuteNonQuery();

    command.CommandText = "INSERT INTO integers VALUES (3, 4), (5, 6), (7, 8);";
    executeNonQuery = command.ExecuteNonQuery();

    command.CommandText = "SELECT foo, bar FROM integers";
    var reader = command.ExecuteReader();

    command.CommandText = "COPY (SELECT * FROM integers) TO 'result-snappy.parquet' (FORMAT 'parquet');";
    executeNonQuery = command.ExecuteNonQuery();
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

Thanks for your effort bringing DuckDB to .NET!

**Comment by Giorgi** [comment]
I think it is the same issue as [Copy table to parquet does not work in Node.js environment](https://github.com/duckdb/duckdb/issues/1977)

As stated there:
> Yes, we are currently not shipping the Parquet extension with the node client. We probably should do that.

See also: [How to build a static library with extensions](https://github.com/duckdb/duckdb/issues/2176)

**Comment by mmauri** [comment]
Thanks, 
Let's hope that they include the extensions on the C++ API, as they do in the Python/R packages.

**Comment by SartorialOffense** [comment]
So they were kind enough to add it in by default:

https://github.com/duckdb/duckdb/pull/2563

I pulled out the new DLL and tested it with a Parquet file in your sample application.

**Comment by Giorgi** [comment]
Did it work?

**Comment by SartorialOffense** [comment]
Yup!

**Comment by mmauri** [comment]
Great news!! Thanks Sartorial, for your help on the duckdb repo!

**Comment by SartorialOffense** [comment]
Happy to help! I need it for a project I am working on right now.
