### ISSUE TITLE
Enable Nullable option for the project

### ISSUE THREAD

**Issue by bykka** [Giorgi/DuckDB.NET#131]
It is simpler to notice when methods return null values

For example: the method returns null but it is not clear by the method's declaration
<img width="930" alt="image" src="https://github.com/Giorgi/DuckDB.NET/assets/489997/bc6b6d60-c8f3-4b5e-8073-4f7f8b686257">

**Comment by Seddryck** [comment]
New attempt in #146

**Comment by Giorgi** [comment]
#146 merged.
