### ISSUE TITLE
Is not support .NET Framework 4.8.1 ?

### ISSUE THREAD

**Issue by kjyoffice** [Giorgi/DuckDB.NET#137]
Hello,
my project is based .NET F/W 4.8.1
my project attach DuckDB.NET before create new console project.
nuget package download "DuckDB.NET.Data.Full"

test code write...
but connect fail...

```C#
// Program.cs
// ...
static void Main(string[] args) {

     new DuckDBConnection("Data Source=:memory:").Open();

}
// ...
```

error message is "duckdb dll import failed"
view build directory, not exist "runtimes" directory

is not support .NET Framework 4.8.1 ?

Thanks.

**Comment by Giorgi** [comment]
The library targets .Net Standard 2.0 so it definitely supports .Net Framework 4.8.1

The thing is though that the runtimes feature is only supported by `PackageReference` and not `packages.config`. You should either convert your NuGet references to `PackageReference` or copy the native library manually to the bin folder.

**Comment by kjyoffice** [comment]
@Giorgi 
You advised it work! 😆
Thanks
