### ISSUE TITLE
Sample project does not run - Null ref exception

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#14]
If I try to run the sample project, I get a null ref exception on this line: https://github.com/Giorgi/DuckDB.NET/blob/a689f76d9661015438b574accd21e3884c418c3a/DuckDB.NET/DuckDBNativeObjects.cs#L81

**Comment by Giorgi** [comment]
@travis-leith Which version of the DuckDB.NET library and DuckDB itself do you use? There were some changes made on the DuckDB side that require using the latest version of DuckDB.NET.

**Comment by travis-leith** [comment]
@Giorgi , just cloning the repo and running the sample project.
At first I thought it was because the dll included in the sample project is out of date. So I downloaded the latest (0.2.9). Now I get 
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
`

From your comment on the other issue, I see that `idx_t rows_changed` was added[ 3 months ago](https://github.com/duckdb/duckdb/commit/325075bf059f2a3f567503f2c31ac45c23c34a22).

However, I see that `void *internal_data` was added [1 month ago](https://github.com/duckdb/duckdb/commit/dd2801fad08931440319bd3e8c9c889f63e4b765). Does the more recent change affect the size of the resulting type? I am a bit out of my depth when it comes to the native stuff.

**Comment by Giorgi** [comment]
Can you try using version 0.2.8 and see if it works?

**Comment by travis-leith** [comment]
0.2.8 does indeed work fine.

**Comment by Giorgi** [comment]
Fixed in ec533b626f280b0b36902c7496759f5e6d58b950
