### ISSUE TITLE
Allow GetXXX/GetFieldValue methods to read data for other numeric types.

### ISSUE THREAD

**Issue by Giorgi** [Giorgi/DuckDB.NET#147]
Based on #142

**Comment by DanCory** [comment]
FYI you should probably get an InvalidCastException if the conversion is not supported. See https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.getint64?view=netcore-3.1#system-data-common-dbdatareader-getint64(system-int32)

**Comment by Giorgi** [comment]
`GetFieldValue<T>` should support this scenario too.

**Comment by Giorgi** [comment]
This is now implemented in develop.
