### ISSUE TITLE
Exception when query empty rows

### ISSUE THREAD

**Issue by Cricle** [Giorgi/DuckDB.NET#148]
![image](https://github.com/Giorgi/DuckDB.NET/assets/26201412/d332a163-c8f1-424a-bcf6-275b8b0e7d24)
The query is 

```sql
SELECT 1 FROM "cursor" WHERE "name" = '*'
```

![image](https://github.com/Giorgi/DuckDB.NET/assets/26201412/5d514be4-fcfb-4e95-90ce-8efdb3d0ba71)

![image](https://github.com/Giorgi/DuckDB.NET/assets/26201412/bf13b589-a8ee-4d96-932f-3edd2c73b287)

**Comment by Giorgi** [comment]
Did you set the command text? I think you aren't using `existsSql` variable

**Comment by Cricle** [comment]
You are right, I forgot to send the SQL, sorry
