### ISSUE TITLE
Use `Appender` throw Not implemented Error: Unimplemented type for cast (INT64 -> INT64)”

### ISSUE THREAD

**Issue by Cricle** [Giorgi/DuckDB.NET#150]
![image](https://github.com/Giorgi/DuckDB.NET/assets/26201412/8222aeaa-941d-44c2-bb09-42a1e669ebdc)

Actually the value is DateTime type

StackTrace:
```
   at DuckDB.NET.Data.DuckDBAppender.ThrowLastError(DuckDBAppender appender)
   at DuckDB.NET.Data.DuckDBAppenderRow.Append[T](T value)
```

**Comment by Giorgi** [comment]
Can you post your table definition and your code that causes the error?

**Comment by Giorgi** [comment]
Closing. If still having the problem please provide the requested details.
