### ISSUE TITLE
Some flaws in the CICD pipeline

### ISSUE THREAD

**Issue by Seddryck** [Giorgi/DuckDB.NET#154]
When you're building the library with GitHub Actions, 

- [ ] the Ubuntu image is trying to upload the artifacts (it shouldn't)
- [ ] the Ubuntu image is trying to upload the artifacts **before** the tests
- [ ] SonarCloud / Build and analyze (pull_request) is failing

**Comment by Giorgi** [comment]
I think Sonar scanned the correct version on the last PR.

**Comment by Seddryck** [comment]
Yes sounds good
