### ISSUE TITLE
Support for motherduck

### ISSUE THREAD

**Issue by darrenkeydata** [Giorgi/DuckDB.NET#157]
Can you add support for motherduck connection strings?

https://motherduck.com/docs/authenticating-to-motherduck

**Comment by Giorgi** [comment]
In theory, I could but I'm not sure if the MotherDuck connection strings are supported by the ducdkb native library or some other library on top of it.

**Comment by Giorgi** [comment]
@darrenkeydata Great! Can you send a PR to update the ReadMe to explain how to get it working?
