### ISSUE TITLE
Allow passing unused parameters to parameterized queries

### ISSUE THREAD

**Issue by roee88** [Giorgi/DuckDB.NET#158]
## Description

Avoid failing when more-than-expected parameters are specified in a parameterized query. For example, if a user specifies 5 named parameters but the query only uses 3, don't fail because there are use cases where this is expected.

Example use cases that will be enabled by this change:
1. System provided parameters to ad-hoc user queries (which may or may not use all parameters)
2. Multi-statement commands with named (also positional?) parameters on different statements
   ```sql
   SELECT 1 WHERE $x = 1; SELECT 2 WHERE $y = 2;
   ```

## Desired behavior

System.Data.SQLite behavior is as expected and accepts the additional `y` parameter

```csharp
using var connection = new SQLiteConnection("Data Source=:memory:");
connection.Open();
using var command = connection.CreateCommand();
command.CommandText = "SELECT 1 WHERE $x = 1;";
command.Parameters.Add(new SQLiteParameter("$x", DbType.Int32) { Value = 1 });
command.Parameters.Add(new SQLiteParameter("$y", DbType.Int32) { Value = 2 });
object result = command.ExecuteScalar();
Assert.AreEqual(1L, result);
```

## Current behavior

```csharp
using var connection = new DuckDBConnection("Data Source=:memory:");
connection.Open();
using var command = connection.CreateCommand();
command.CommandText = "SELECT 1 WHERE $x = 1;";
command.Parameters.Add(new DuckDBParameter("x", 1));
command.Parameters.Add(new DuckDBParameter("y", 2));
command.ExecuteScalar();
```

A `System.InvalidOperationException` is thrown

```csharp
System.InvalidOperationException: Invalid number of parameters. Expected 1, got 2
```

**Comment by Giorgi** [comment]
Does `Microsoft.Data.Sqlite` allow it?

**Comment by roee88** [comment]
> Does `Microsoft.Data.Sqlite` allow it?

Yes

**Comment by Giorgi** [comment]
What about other database providers such as SqlClient and Npgsql?

**Comment by roee88** [comment]
I don't know, does it really matter? The main claim here isn't that others allow it so this library should too, but rather that there are valid use cases for it, as I mentioned.

**Comment by Giorgi** [comment]
This is now live on NuGet
