### ISSUE TITLE
DuckDBConnection.CreateAppender not dealing correctly when table with special characters

### ISSUE THREAD

**Issue by jhudler** [Giorgi/DuckDB.NET#162]
Hello,

First of all, thank you for this library. Very simple to use and straightforward!

---

# The Issue

The following code will fail when trying to create an appender:

```cs
using var conn = new DuckDB.NET.Data.DuckDBConnection("Data Source=:memory:");
conn.Open();
var specialTableName = "SPÉçÏÃL - TÁBLÈ_";
using (var cmdCreateTable = conn.CreateCommand())
{
    cmdCreateTable.CommandText = @$"CREATE TABLE ""{specialTableName}"" (SomeField TEXT)";
    cmdCreateTable.ExecuteNonQuery();
}

try
{
    using (var appender = conn.CreateAppender(specialTableName))
    {

    };    
    Console.WriteLine("Passed!");
}
catch (Exception e)
{
    Console.Error.WriteLine($"Failed to retrieve schema: {e.Message}");
}
```

Stack Trace:
```
Failed to retrieve schema: DuckDB.NET.Data.DuckDBException (0x80004005): Catalog Error: Table "main.SP????L - T?BL?_" could not be found
   at DuckDB.NET.Data.DuckDBAppender.ThrowLastError(DuckDBAppender appender)
   at DuckDB.NET.Data.DuckDBConnection.CreateAppender(String schema, String table)
   at DuckDB.NET.Data.DuckDBConnection.CreateAppender(String table)
```

It seems that the `CreateAppender` is not correctly converting the string to the correct encoding before calling the native API.

If you have any guidance on this, I can provide a PR.

**Comment by Giorgi** [comment]
In the `CreateAppender` method the schema and table need to be converted to utf8 with `Utils.ToUnmanagedString`

**Comment by jhudler** [comment]
Apparently easier than I thought. Just followed the pattern used in 3aea4640d9ea761ea6aab457a840bc583e440ddf. Made the PR #163 - hope is fine.
