### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#17]
Just looking at the documentation here: https://duckdb.org/docs/api/c/types
I noticed the following

> Note that duckdb_value_varchar and duckdb_value_blob require the result to be de-allocated using duckdb_free.

Is this something we have to worry about in .net? I see for instance the following line of code in the data reader

```c#
        public override string GetString(int ordinal)
        {
            return PlatformIndependentBindings.NativeMethods.DuckDBValueVarchar(_queryResult, ordinal, _currentRow);
        }
```

**Comment by Giorgi** [comment]
Fixed by f2be8cb512ac718b6db56fa6daad8af7f7e0ed4e
