### ISSUE TITLE
Add possibility to append byte[]

### ISSUE THREAD

**Issue by sashapodgoreanu** [Giorgi/DuckDB.NET#181]
DuckDBAppender doesn't have the possibility to append an array of bytes.

**Comment by StanEgo** [comment]
And SqlParameter does not support too. And also would be nice to add UUID support.

**Comment by Giorgi** [comment]
@StanEgo You can write `byte[]` to the database: https://github.com/Giorgi/DuckDB.NET/blob/0610950b92b0a1db73ab5ba12f9433bdd32f95fa/DuckDB.NET.Test/Parameters/BlobParameterTests.cs#L103
