### ISSUE TITLE
version 1.0 Binder Error: Referenced column "x" not found in FROM clause!

### ISSUE THREAD

**Issue by jp200k** [Giorgi/DuckDB.NET#193]
When using DuckDB 1.0 in C#, I got the following error: 
Binder Error: Referenced column "city" not found in FROM clause!
LINE 1: ..._lo, temp_hi, prcp, date, id) VALUES (@city, @temp_lo, @temp_hi, @prcp, @date,...

my statement is:  INSERT INTO weather (city, temp_lo, temp_hi, prcp, date, id) VALUES (@city, @temp_lo, @temp_hi, @prcp, @date, @id );
where the DuckDBParameter are all correctly assigned, including ParameterName, SourceColumn, DateType and Value. 

If NOT using parameters and hard coding above insert statement, it works well. When using parameters, I got above error. 
Searching the web, I found other users got similar error message but their causes might be different. However, here the "FROM clause" is not relative. 

Thank you for your hard work.

**Comment by Giorgi** [comment]
@jp200k Can you format the code as a code snippet? It's hard to read now.

**Comment by Cricle** [comment]
According to duckdb doc [prepared_statements](https://duckdb.org/docs/sql/query_syntax/prepared_statements), no start with `@` paramter accept. Can you try to use like `$city`? @jp200k

**Comment by brendonparker** [comment]
This is a common scenario people run into (including myself). As @Cricle stated, the parameters need to be prefixed with `$` not `@`. Otherwise you get the referenced error, which is a little misleading.

@jp200k so instead of:
```sql
INSERT INTO weather (city, temp_lo, temp_hi, prcp, date, id) 
VALUES (@city, @temp_lo, @temp_hi, @prcp, @Date, @id);
```
try:
```sql
INSERT INTO weather (city, temp_lo, temp_hi, prcp, date, id) 
VALUES ($city, $temp_lo, $temp_hi, $prcp, $Date, $id);
```

**Comment by Giorgi** [comment]
@brendonparker Thanks for confirming that this is not a DuckDB.NET issues. This is documented in the docs: https://duckdb.net/docs/basic-usage.html#parameterized-statements
