### ISSUE TITLE
Which version of DuckDB is supported?

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#2]
I can't seem to find in your code (please excuse my incompetence) where you bring in the external functionality. I can only find .cs files. Does this mean this library assumes a prior installation of DuckDB, and if so, which version(s) is(are) supported?

**Comment by Giorgi** [comment]
It assumes that the DuckDB binary (dll or dylib file) is somewhere where it can find, i.e. either in %PATH% or in the same folder as the running executable.

As for the supported versions, when I started this project DuckDB was at version 0.2.2 I think. If you find issues with the newer version of the library let me know and I will try to fix it.

**Comment by Giorgi** [comment]
The external functionality is in NativeMethods.Windows.cs and NativeMethods.MacOS.cs files

**Comment by travis-leith** [comment]
ok thanks. I'll do some testing with the latest version and if it works I will close this issue.

**Comment by travis-leith** [comment]
I got it to work with the latest version (0.2.5) but in testing I noticed that error messages are not detailed enough. I will open a separate issue for that.
