### ISSUE TITLE
Parquet Support

### ISSUE THREAD

**Issue by karthikmallireddy** [Giorgi/DuckDB.NET#20]
How to read Parquet files directly using the Duckdb.net

**Comment by Giorgi** [comment]
Can you describe what issues do you have with reading Parquet files?

**Comment by karthikmallireddy** [comment]
![image_2021_11_22T09_24_44_896Z](https://user-images.githubusercontent.com/5372956/142836805-c4cddcdd-f4ab-4be1-997d-fe62a4ab3eec.png)



I'm getting the attached error while reading the parquet file.

**Comment by Giorgi** [comment]
Does the same code work when you use native duckdb library?

**Comment by karthikmallireddy** [comment]
Yes with the CLI I can able to execute the same query.

**Comment by Giorgi** [comment]
Which version of duckdb.dll do you have in your project?

**Comment by karthikmallireddy** [comment]
V2.9.1

**Comment by Giorgi** [comment]
Try using 0.3.1

**Comment by ravi27may** [comment]
Hi Giorgi,

Where can we download 0.3.1 version. The source code still generates 0.2.9.1 version.

Also, the newer version works with reading data from aws s3 with s3 endpoint. Could you please help if you have any sample that will really helpful.

**Comment by Giorgi** [comment]
Glad that it works for you.

**Comment by karthikmallireddy** [comment]
I'm not able to find 0.3.1 Version where do you find that DLL, Can you please share that link.

**Comment by Giorgi** [comment]
You can download it from https://github.com/duckdb/duckdb/releases/tag/v0.3.1

**Comment by karthikmallireddy** [comment]
Is it possible for you to share a working copy with parquet here, It would be great help thanks in advance.

**Comment by Giorgi** [comment]
Download Windows build from the link above.

**Comment by karthikmallireddy** [comment]
Getting a lot of errors while doing it, Is there a way can you please send the working project with Duck db 0.3.1 if possibly only.

**Comment by ravi27may** [comment]
@karthikmallireddy  I used the same code (in a console) which you mentioned above, what errors you are facing?
