### ISSUE TITLE
Should the `RuntimeIdentifiers` property `osx` change to `osx-x64`?

### ISSUE THREAD

**Issue by Cricle** [Giorgi/DuckDB.NET#201]
https://github.com/Giorgi/DuckDB.NET/blob/18decabf2e794881af4c566982aaa6ff4106eef0/DuckDB.NET.Bindings/Bindings.csproj#L7

https://github.com/Giorgi/DuckDB.NET/blob/18decabf2e794881af4c566982aaa6ff4106eef0/DuckDB.NET.Bindings/Bindings.csproj#L24

According to [rid-catalog#macos](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#macos-rids) `osx-x64` is `macOS RIDs`

**Comment by Cricle** [comment]
Drafted modifications on #202

**Comment by Giorgi** [comment]
In that case I would need to have osx-x64 and osx-arm64 which probably means including libduckdb.dylib twice in the NuGet package.

**Comment by Giorgi** [comment]
I haven't looked into Native AOT yet. I'll close this issue and we can come back to it if needed.

**Comment by Cricle** [comment]
Ok
