### ISSUE TITLE
Add support for Cancel Command

### ISSUE THREAD

**Issue by kannenberg** [Giorgi/DuckDB.NET#204]
Add support for canceling asynchronous command when using CancellationToken.

I'm trying to cancel the command when the token is canceled. We are using CancellationTokenRegistration to cancel the command when cancellation is triggered.

This behavior is expected because when the user cancels the HTTP request we fire a CancellationToken to cancel all executing commands. However, we noticed that the Command's Cancel method was not implemented.

https://github.com/Giorgi/DuckDB.NET/blob/9c0dbf81801ae584a32c010f5a372846f3a72618/DuckDB.NET.Data/DuckDBCommand.cs#L72

Do we have any plans to implement this method or any other alternative to this requirement?

Thank you for your attention.

**Comment by Giorgi** [comment]
There is a way to interrupt execution with [duckdb_interrupt](https://duckdb.org/docs/api/c/api#duckdb_interrupt) but I haven't implemented it.

**Comment by kannenberg** [comment]
Is it possible to extend your library and implement this method or do you suggest any other approach for immediately stopping the SQL command?

**Comment by Giorgi** [comment]
Yes, it's possible if I find free time or if you send a PR.

**Comment by kannenberg** [comment]
We understand the issue of roadmap priorities, but we can help with implementation, as long as you give us a small orientation to start from.

We are very excited about using DuckDB in our process mining solution. Using DuckDB has been a great advantage and satisfaction for us.

But, like any solution that grows quickly, we are facing scalability problems and we will possibly migrate to MotherDuck, but that is still a little far away. In any case, we work with our backend in C# and we intend to continue like this.

We don't have much experience with Interop, but we are willing to learn.

**Comment by Giorgi** [comment]
Implemented in [fe02f4c](https://github.com/Giorgi/DuckDB.NET/commit/fe02f4c32240f252b314c06249fdba5e83818d7a)
