### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by netnr** [Giorgi/DuckDB.NET#205]
An error occurred after multiple times

```csharp
string v2 = null;
using var appender = connection.CreateAppender("files");
for (var i = 1; i <= 2_000_000; i++)
{
    var name = i % 5 == 0 ? $"{Guid.NewGuid()}.py" : Guid.NewGuid().ToString();
    appender.CreateRow()
        .AppendValue(i).AppendValue(name)
        .AppendValue(i).AppendValue(v2)
        .EndRow();
}
```

No problem if it is not null
```csharp
string v2 = null;
using var appender = connection.CreateAppender("files");
for (var i = 1; i <= 2_000_000; i++)
{
    var name = i % 5 == 0 ? $"{Guid.NewGuid()}.py" : Guid.NewGuid().ToString();
    appender.CreateRow()
        .AppendValue(i).AppendValue(name)
        .AppendValue(i).AppendValue(v2 ?? "") // not null
        .EndRow();
}
```

**Comment by Giorgi** [comment]
This is fixed in c074b18b2901e7384f4c6f6068a5ca666131c64b commit. I'll push it on NuGet in a week or two. In the meantime you can install it from https://github.com/Giorgi/DuckDB.NET/pkgs/nuget/DuckDB.NET.Data.Full

**Comment by muralimadduTR** [comment]
Hello, 

I'm facing similar issue, one novice question please, may I know how can I download the nuget package mentioned in above link, tried to find but couldn't able to?

https://github.com/Giorgi/DuckDB.NET/pkgs/nuget/DuckDB.NET.Data.Full

TIA.

**Comment by Giorgi** [comment]
I just pushed 1.0.2 to NuGet, it includes a fix for this issue.

**Comment by Giorgi** [comment]
@brasio Can you share the code that throws that exception?
