### ISSUE TITLE
DuckDBAppender: Support data type enum

### ISSUE THREAD

**Issue by eschgi** [Giorgi/DuckDB.NET#209]
Hello,

i tried to use today the DuckDBAppender class to insert an enum value to the database, but i got a not implemented exception: 
Writing Enum to data chunk is not yet supported. I have seen the exception is thrown by the VectorDataWriterFactory class.

Would duck db itself support this? Is just the implementation missing?

Kind regards

**Comment by Giorgi** [comment]
It's supported by DuckDB but not implemented in DuckDB.NET.

**Comment by eschgi** [comment]
@Giorgi Do you plan to support this soon? Do you would accept a pull request?

**Comment by Giorgi** [comment]
Yes, I'll accept a PR.

**Comment by Giorgi** [comment]
@eschgi Still interested in sending a PR?

**Comment by eschgi** [comment]
Hi @Giorgi, yes I'm still interested, but i need to see when i can work on this. I have only compiled the project locally so far, it has worked so far, but unfortunately I haven't had time to take a closer look at everything yet.

**Comment by Giorgi** [comment]
Thanks for the PR @eschgi
