### ISSUE TITLE
Aws S3 support

### ISSUE THREAD

**Issue by ravi27may** [Giorgi/DuckDB.NET#21]
Hi,

Am trying to read the parquet file data from aws s3 (similar to specified in the link provided https://github.com/duckdb/duckdb/blob/1fbc35f37e2b5b5e641ae0e0cb145078621c0c7b/test/sql/copy/parquet/test_parquet_remote.test) but it says the file didn't found.  

Could someone please help how to read the data from aws s3 file

**Comment by Giorgi** [comment]
Does the same work when you run it from duckdb shell?

**Comment by ravi27may** [comment]
Yes Giorgi, it worked using the shell but in linux

**Comment by Giorgi** [comment]
@ravi27may Which version of duckdb.dll did you try it with?

**Comment by Giorgi** [comment]
@ravi27may To load files from HTTPS or S3 DuckDb needs to be compiled with HTTPFS extension: https://github.com/duckdb/duckdb/issues/1457#issuecomment-983606089

**Comment by ravi27may** [comment]
Hi Giorgi,

Am using the 0.3.1 version. so is this version already have httfs extension included any idea

**Comment by Giorgi** [comment]
I don't think 0.3.1 has `BUILD_HTTPFS_EXTENSION=1`

**Comment by ravi27may** [comment]
@Giorgi - how can we build the with httpfs extension to duckdb.dll. Could you please help me

**Comment by Giorgi** [comment]
That question belongs to the [DuckDB](https://github.com/duckdb/duckdb/) repo

**Comment by karthikmallireddy** [comment]
@Giorgi Since duckdb 0.5.1 is released, if possible can you provide us an example with s3 file reading?

**Comment by mikeTWC1984** [comment]
I think DuckDB never includes httpfs in their precompiled binaries. It can be installed by executing "INSTAL httpfs" sql command (it will download extension ) and then "LOAD httpfs".

**Comment by Giorgi** [comment]
Closing as this issue isn't related to .Net bindings.
