### ISSUE TITLE
System.AccessViolationException when I run a parameterized query

### ISSUE THREAD

**Issue by neilfromcork** [Giorgi/DuckDB.NET#212]
I'm getting the following error when I run a parameterized query:

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Code is:
```cs
using (DuckDBConnection conn = new DuckDBConnection(connectionString))
                {
                    if (!conn.State.Equals(ConnectionState.Open)) conn.Open();
                    string sql = "SELECT * FROM td_catalog_source where ctl_id=$ctlid;";
                    

                    using DuckDBCommand command = conn.CreateCommand();
                    command.CommandText = sql;

                    command.Parameters.Add(new DuckDBParameter("ctlid", 2));
                    
                    

                    using var result=command.ExecuteReader();
}
```

Using .Net 8.0, DuckDB.NET.Data.Full 1.0.2, DuckDB.NET.Bindings.Full 1.0.2

**Comment by Giorgi** [comment]
Does this happen when you are debugging the code? Are you using Rider?

**Comment by neilfromcork** [comment]
Yes, while debugging. And yes, I'm using Rider.

**Comment by neilfromcork** [comment]
..works fine when using positional parameters

**Comment by Giorgi** [comment]
Check this for a workaround: https://github.com/Giorgi/DuckDB.NET?tab=readme-ov-file#known-issues
