### ISSUE TITLE
In windows env, can not load the duckdb.dll, help!!!

### ISSUE THREAD

**Issue by zhui19871** [Giorgi/DuckDB.NET#219]
System.TypelnitializationException."DuckDB.NET.Data.DuckDBConnectionStringBuilder”的类型初始值设定项引发异常。 --->System.DllNotFoundException: 无法加载 DLL“duckdb":找不到指定的模块。(异常来自HRESULT:0x8007007E)。
在DuckDB.NET.Native.NativeMethods.Configuration.DuckDBConfigCount()在 DuckDB.NET.Data.DuckDBConnectionStringBuilder..cctor()

**Comment by Giorgi** [comment]
If you are targeting .NET Framework, copy duckdb.dll to the bin folder.

**Comment by zhui19871** [comment]
I have already copy to bin folder, but find in net framework 4.81 not working。

**Comment by Giorgi** [comment]
Did you copy it to bin folder or bin\Debug? You can also search for this issue at the dotnet channel in DuckDB Discord: https://discord.com/channels/909674491309850675/1051088721996427265
