### ISSUE TITLE
Feature request: Suppport for DbConnection.StateChange event handler

### ISSUE THREAD

**Issue by ylorph** [Giorgi/DuckDB.NET#220]
Relevant [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.statechange?view=net-8.0) 

I think only the follwing needs support looking at DBConnection for sqlite 

* open -> closed
* closed -> open

**Comment by Giorgi** [comment]
Implemented in https://github.com/Giorgi/DuckDB.NET/pull/221
