### ISSUE TITLE
How do I get the progress of a long query?

### ISSUE THREAD

**Issue by nsulikowski** [Giorgi/DuckDB.NET#224]
Similar to how the CLI shows a progress bar, bur from the API.

**Comment by Giorgi** [comment]
You can use [DuckDBQueryProgress](https://duckdb.net/api/duckdb.net.native.nativemethods.startup#DuckDB_NET_Native_NativeMethods_Startup_DuckDBQueryProgress_DuckDB_NET_Native_DuckDBNativeConnection_) method

**Comment by nsulikowski** [comment]
Shouldn’t this be an event in c#
may be in the connection object?

**Comment by Giorgi** [comment]
DuckDB doesn't have any callback to notify that progress has changed and I didn't want to do polling.
