### ISSUE TITLE
RegisterTableFunction errors handling

### ISSUE THREAD

**Issue by VitaliyMF** [Giorgi/DuckDB.NET#234]
It is a bit unclear what to do if something inside `resultCallback` goes wrong.

For example, let's assume that some TVFs uses another ADO.NET provider to execute an SQL query (via ExecuteReader) -- this is performed inside `resultCallback` -- and each `mapperCallback` call moves forward a data reader. An error can occur in both handlers, and currently when an exception is thrown inside `resultCallback` this simply crushes a NET8 app (at least, on Windows).

Two things in this regard:

1. Maybe [RegisterTableFunctionInternal](https://github.com/Giorgi/DuckDB.NET/blob/develop/DuckDB.NET.Data/DuckDBConnection.TableFunction.cs#L71) should wrap `resultCallback` with own function with try-catch block to guarantee that app will not suddenly crush?
2. What is the most appropriate behaviour should be in case of exception inside `resultCallback`? As a variant, this can be return of the 'stub' result - like zero `ColumnInfo` list (or 1 string column if zero columns are not allowed), and `mapperCallback` that re-throws an exception that occurs inside `resultCallback` as it is thrown correctly when `DuckDB.NET.Data.DuckDBCommand.ExecuteDbDataReader` is called.

Both these things can be implemented outside DuckDB.NET, however it makes sense to implement them inside the library to make its usage more safe.

**Comment by VitaliyMF** [comment]
Sure, let me try it - to check that it works as we expect :)

**Comment by VitaliyMF** [comment]
@Giorgi what I'm trying to do in [Bind](https://github.com/Giorgi/DuckDB.NET/blob/develop/DuckDB.NET.Data/DuckDBConnection.TableFunction.cs#L103):
```
		TableFunction tableFunctionData;
		try {
			tableFunctionData = functionInfo.Bind(parameters);
		} catch (Exception ex) {
			using (var errMsgHandle = ex.Message.ToUnmanagedString())
			{
				NativeMethods.TableFunction.DuckDBFunctionSetError(info, errMsgHandle);
			}
			return;
		} finally {
			foreach (var parameter in parameters) {
				((DuckDBValue)parameter).Dispose();
			}
		}
```
However, test fails with the following exception:
```
DuckDB.NET.Data.DuckDBException : INTERNAL Error: Failed to bind "demo_err": Table function must return at least one column 
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

You definitely know DuckDB C API better, have I missed something obvious? I may commit changes I made to my fork if you would like to try it by yourself.

Does this means that in the case of exception I should anyway call `DuckDBBindAddResultColumn` (add some 'stub' string column for instance) and `DuckDBBindSetBindData` anyway?

**Comment by Giorgi** [comment]
Yes, you should provide at least one column.

**Comment by VitaliyMF** [comment]
`duckdb_bind_set_error` works like a charm. Only inconsistency I see that when exception occurs inside `resultCallback` exception type is lost (DuckDBException is thrown) and exception inside `mapperCallback` comes as is (it just works without any changes). Maybe it makes sense to wrap 

```
            if (tableFunctionBindData.DataEnumerator.MoveNext())
            {
                tableFunctionInfo.Mapper(tableFunctionBindData.DataEnumerator.Current, writers, size);
            }
```

too and re-throw DuckDBException too?..
