### ISSUE TITLE
Implement an Entity Framework provider

### ISSUE THREAD

**Issue by MovGP0** [Giorgi/DuckDB.NET#240]
## Motivation

Many existing code bases use Entity Framework instead of ADO.NET. Implementing an Entity Framework Provider would simplify migrating existing code to DuckDB and also make it easier to write new code that utilizes DuckDB.

I made a list on what would be required, but the effort required far exeeds what I would be able to do 😔

----

The following steps would be required:

## Preliminary Research

EF Core Provider Documentation:

- [EF Core Provider Design](https://docs.microsoft.com/ef/core/providers/)
- [EF Core provider samples (e.g., the SQLite provider, or open-source 3rd-party providers)](https://github.com/dotnet/efcore)

## Implement base classes and interfaces:

- [ ] `Microsoft.EntityFrameworkCore.Storage`
- [ ] `Microsoft.EntityFrameworkCore.Infrastructure`
- [ ] `Microsoft.EntityFrameworkCore.Query`
- [ ] `RelationalDatabaseProvider`
- [ ] `RelationalConnection`
- [ ] `RelationalCommandBuilderFactory`
- [ ] `TypeMappingSource`
- [ ] `MigrationsSqlGenerator`

### Data Access Layer:

The ADO.NET provider must expose 
- [x] `DbConnection`
- [x] `DbCommand`
- [x] `DbDataReader`

### Dialect and SQL Generation Layer:

Implement generators that produce valid DuckDB SQL from EF Expressions.

- [ ] `QuerySqlGenerator`
- [ ] `MigrationsSqlGenerator`

### Migrations Support (Optional):

Implement classes that provide DuckDB DDL schema migrations:

- [ ] `HistoryRepository` (for storing migration history in DuckDB)
- [ ] `MigrationsModelDiffer`
- [ ] `MigrationsSqlGenerator`

### Implement `DuckDbOptionsExtension` and provider options:

Implement types to hold DuckDB-specific configurations (file paths, in-memory mode, etc.).

- [ ] `DuckDBContextOptions` class
- [ ] `IDbContextOptionsExtension` (e.g., `DuckDbOptionsExtension`)
- [ ] `UseDuckDb()` extension methods for `DbContextOptionsBuilder`

### `DuckDbDatabaseProvider` Services:

- [ ] Register provider services via `DuckDbDesignTimeServices` or `DuckDbDbContextOptionsBuilder`.
- [ ] Implement `DuckDbDatabaseProvider` class that sets up service dependencies (SQL generator, type mappings, etc.).

### Connection and Command Classes:

Implement wrappers the low-level DuckDB ADO.NET command execution.

- [ ] `DuckDbConnection` (inherits `RelationalConnection`)
- [ ] `DuckDbCommandBuilder`
- [ ] `DuckDbCommandExecutor`

### Type Mapping:

Implement mapping from EF Core’s ClrType and `RelationalTypeMapping` data to DuckDB column types.

- [ ] `DuckDbTypeMappingSource`

### SQL Generation:

- [ ] Implement `DuckDbSqlGenerationHelper` for quoting identifiers and delimiters.
- [ ] Implement `DuckDbQuerySqlGenerator` that translates LINQ expression trees into DuckDB-compatible SQL.

### Migrations (optional):

Implement generator to translate EF model changes into DuckDB DDL (CREATE TABLE, ALTER TABLE, etc.).
- [ ] `DuckDbMigrationsSqlGenerator`

Implement migration history tracking in a metadata table
- [ ] `DuckDbHistoryRepository`

**Comment by Giorgi** [comment]
Have you seen https://github.com/Giorgi/DuckDB.NET/discussions/172 ?

**Comment by MovGP0** [comment]
> Have you seen #172 ?

Thank you. I was only checking issues rather that discussions.

Would you prefer copying this check list to the discussion and closing this issue?
