### ISSUE TITLE
DuckDBConnection.Open Throwing 'The type initializer for 'DuckDB.NET.Data.DuckDBConnectionStringBuilder' threw an exception.'

### ISSUE THREAD

**Issue by TheLastArchive** [Giorgi/DuckDB.NET#241]
I've tried with the two different NuGet packages 'DuckDB.NET.Data.Full' and 'DuckDB.NET.Bindings.Full' 

When I attempt to open the DuckDB connection like so:
`using (var connection = new DuckDBConnection("DataSource=:memory:"))
{
    connection.Open();
    ...
}`

I get the exception listed in the title:

The type initializer for 'DuckDB.NET.Data.DuckDBConnectionStringBuilder' threw an exception.

I've followed along in the debugger and here is where everything goes wrong in DuckDBConnection.cs

`internal DuckDBConnectionString ParsedConnection => parsedConnection ??= DuckDBConnectionStringBuilder.Parse(ConnectionString);`

ConnectionString is set to `DataSource=:memory:`

I tried following a similar issue that's been closed out and didn't really resolve my issue. Is there any additional setup that I may be missing? I followed the documentation to the best of my ability .

**Comment by Giorgi** [comment]
What type of project are you building? Is it a Blazor app by any chance?

**Comment by TheLastArchive** [comment]
@Giorgi Apologies for the late reply, but no it's not a Blazor app. I did read through #169

**Comment by Giorgi** [comment]
Can you post the full exception? Including the InnerException.

**Comment by TheLastArchive** [comment]
Exception Message = The type initializer for 'DuckDB.NET.Data.DuckDBConnectionStringBuilder' threw an exception.

Exception StackTrace StackTrace = "   at DuckDB.NET.Data.DuckDBConnectionStringBuilder.Parse(String connectionString) in /_/DuckDB.NET.Data/DuckDBConnectionStringBuilder.cs:line 68\r\n   at DuckDB.NET.Data.DuckDBConnection.get_ParsedConnection() in /_/DuckDB.NET.Data/DuckDBConnection.cs:lin...

Exception Source = "DuckDB.NET.Data"

InnerException Message= {"Unable to load DLL 'duckdb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

InnerException StackTrace = "   at DuckDB.NET.Native.NativeMethods.Configuration.DuckDBConfigCount()\r\n   at DuckDB.NET.Data.DuckDBConnectionStringBuilder..cctor() in /_/DuckDB.NET.Data/DuckDBConnectionStringBuilder.cs:line 25"

InnerException Source = "DuckDB.NET.Bindings"


It not being able to find the .dll is odd.

**Comment by Giorgi** [comment]
Which version of .NET are you targeting? Did you download duckdb.dll from the official website by any chance? There were some similar issues posted in [discord channel](https://discord.duckdb.org/), did you check them?

**Comment by Giorgi** [comment]
DuckDB.NET.Data and DuckDB.NET.Bindings do not contain the native duckdb.dll. You must download it manually from the official website and put it in the bin folder.

Make sure that your project is x64 and download the correct duckdb.dll - there are x64 and arm builds for Windows.

**Comment by TheLastArchive** [comment]
Apologies for the late response.

I checked the official site and I don't see any downloads for a dll, would it be included in either the cli after I run the exe, or will I need to download the ODBC?

**Comment by Giorgi** [comment]
You can download it from https://duckdb.org/docs/installation/?version=stable&environment=cplusplus&platform=win&download_method=direct&architecture=x86_64 or install DuckDB.NET.Data.Full and copy duckdb.dll manually from the runtimes folder.

**Comment by TheLastArchive** [comment]
Thank you. Unfortunately it seems that the project's platform target is x86, the product is several years old so I doubt switching to x64 would be feasible anytime soon. It seems that DuckDB only supports x64 so I may be out of luck.

**Comment by Giorgi** [comment]
That's right, DuckDB doesn't support x86.
