### ISSUE TITLE
Please provide more detail on error messages

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#3]
I noticed that in comparing CLI error messages, I get a clear descriptive error. When I use this library I just get "DuckDBQuery failed".

Is there any additional error information coming from the external dlls (something similar to what the CLI shows) that can be propagated in .net?

**Comment by Giorgi** [comment]
If this happens when you run one of the `Execute*` methods I think it should be able to read that from [DuckDBResult.ErrorMessage](https://github.com/Giorgi/DuckDB.NET/blob/master/DuckDB.NET/DuckDBNativeObjects.cs#L70) Can you send a PR for that?

**Comment by travis-leith** [comment]
I'll give it a go, but full disclosure: I am not very good at C#. When it comes to .Net, I typically use F#, which is the language I am using this library from. Let's see how I get on.
