### ISSUE TITLE
No results are received with any query

### ISSUE THREAD

**Issue by IvaYan** [Giorgi/DuckDB.NET#31]
Hi. I'm experimenting with DuckDb through C# and it appears that I'm not able to get results of any query.

I receive no syntax or execution error, but no result is returned. I've tried several queries and all of the queries that I run with `ExecuteScalar` return 0 as a value and all of the queries that are expected to return multiple columns return zero columns (i.e. db reader does not iterate over rows). The same queries produce the correct result with DuckDb CLI.

The simplest code is:

```CSharp
await using (var conn = new DuckDBConnection("Data Source=:memory:"))
{
    conn.Open();

    var command = conn.CreateCommand();
    
    command.CommandText = "SELECT 42;";
    var executeScalar = await command.ExecuteScalarAsync();
    Console.WriteLine(executeScalar);
}
```

We expect this query to return 42, but it returns 0.

My setup:
- libduckdb 0.4.0 prebuilt
- DuckDB.NET 0.2.9.1
- macOS with Intel CPU

**Comment by Giorgi** [comment]
Can you try the same project on Windows or Linux?

**Comment by Giorgi** [comment]
Can you upload a simple repro app?

**Comment by Giorgi** [comment]
Can you try [release 0.4.0](https://www.nuget.org/packages/DuckDB.NET.Data/0.4.0#release-body-tab)?

**Comment by Giorgi** [comment]
There is already an issue for that: #37

**Comment by Giorgi** [comment]
@IvaYan The queries work as expected. `ExecuteScalar` should be used with queries like this: `SELECT count(*) from users` 

To get the data from the table use `ExecuteReader` and use the returned reader to get query values.

**Comment by Giorgi** [comment]
@IvaYan Want to send a PR?

**Comment by Giorgi** [comment]
@IvaYan Thanks for finding and fixing the issue.
