### ISSUE TITLE
Connection string failures and utilities

### ISSUE THREAD

**Issue by IvaYan** [Giorgi/DuckDB.NET#42]
We should specify a connection string when creating a connection. We currently support connection strings that look like `DataSource=<location>` or `Data Source=<location>`. However, connection strings like `DataSource = <location>` are not valid because we do not allow spaces around the `=` mark. This does not seem to be a DuckDB requirement actually, for example Microsoft.Data.Sqlite allows such spaces (i.e. connection strings like `"Data Source = :memory:"`. 

So, requirement to have no spaces seems buggy to me. If no one minds, I can fix this.

Another connection string related must-have is a connection string builder. It simplifies connection string formatting because people usually do not remember the format they need to use. Again, if no one minds, I can implement this either.

**Comment by Giorgi** [comment]
@IvaYan Feel free to send a PR for this feature.
