### ISSUE TITLE
Does not work with Dapper

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#5]
For some reason I can't get this to work with Dapper.
As I understand it, Dapper is just a wrapper around ADO.Net so anything that looks like ADO.Net should work, in principle.

When I try to execute something using Dapper, I get "DuckDBOpen failed". I tried to work out a way to find a more detailed error message but was unsuccessful.

I created a branch which demonstrates the error here: https://github.com/travis-leith/DuckDB.NET/tree/show_dapper_error

**Comment by travis-leith** [comment]
Just run the sample project to see the error.

**Comment by Giorgi** [comment]
Fixed.
