### ISSUE TITLE
Not implemented methods to get column data

### ISSUE THREAD

**Issue by IvaYan** [Giorgi/DuckDB.NET#52]
We have some not implemented methods in `DuckDBDataReader`. We need to check whether DuckDb supports these data types and implement the methods for the supported type. Maybe we should throw something like `NotSupportedException` for the types DuckDB does not support.

Here are specific issues for the non-implemented types:

- [x] #54 
- [x] #55 
- [x] #56 
- [x] #57

**Comment by Giorgi** [comment]
What if we treat byte as `char` too?
