### ISSUE TITLE
Implement BLOB type support

### ISSUE THREAD

**Issue by IvaYan** [Giorgi/DuckDB.NET#54]
We need both reading and writing of blob values.

**Comment by Giorgi** [comment]
To pass blob as parameter we need to introduce a new Enum for parameter type (DuckDBType) and use that instead of DbType

**Comment by Giorgi** [comment]
There is but 
- `DbType.Binary` comment says: **A variable-length stream of binary data ranging between 1 and 8,000 bytes.** 
- Every provider has its own DbType enum for custom types and we will need it sooner or later

There is nothing stopping us from using `DbType.Binary` technically but I don't know if that's the right thing to do or not.

**Comment by hazzik** [comment]
This also needs to be documented.

**Comment by Giorgi** [comment]
@hazzik Docs are in this repo: https://github.com/Giorgi/DuckDB.NET-Docs
