### ISSUE TITLE
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'duckdb_open_ext' in shared library 'duckdb'.

### ISSUE THREAD

**Issue by jorisvdstraten** [Giorgi/DuckDB.NET#66]
Hi,

When using the DuckDB.Net package on a Mac M1 I receive the following error on `db.Open()`:
`Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'duckdb_open_ext' in shared library 'duckdb'.`

I've included the duckdb executable in the project directory and set it to copy to output so it's included in the bin/debug folder.

**Comment by Giorgi** [comment]
@jorisvdstraten Did you include libduckdb.dylib?

**Comment by jorisvdstraten** [comment]
No, seems I was confused and included the duckdb executable, sorry about that and thanks for your suggestion.
Now I receive a MacOS permission window error telling the libduckdb.dylib cannot be opened because the developer cannot be verified.

**Comment by Giorgi** [comment]
Do you get that error at runtime?

**Comment by jorisvdstraten** [comment]
Yes.

**Comment by jorisvdstraten** [comment]
I've managed to let it work by opening the bin/debug/libduckdb.dylib by right clicking in the Finder. Seems to be a MacOS permission related issue.
