### ISSUE TITLE
DbProviderFactories.GetFactory fails

### ISSUE THREAD

**Issue by ulissescappato** [Giorgi/DuckDB.NET#67]
Hi!

I get the error below when I try to run:

---
Imports System.Data.Common
---

DbProviderFactories.GetFactory("DuckDB.NET.Data")

Error: System.Data.Entity.Core.ProviderIncompatibleException: 'A null was returned after calling the 'get_ProviderFactory' method on a store provider instance of type 'DuckDB.NET.Data.DuckDBConnection'. The store provider might not be functioning correctly.'

I'm trying to use the Entity Framework.

Thanks!
Ulisses.

**Comment by Giorgi** [comment]
DbProviderFactory Api isn't supported at the time. If you need it, consider sending a PR or supporting the project.

**Comment by bnuzhouwei** [comment]
DbProviderFactory is important for database abstractions, I need it so that i can change store among databases, especilly between clickhouse and duckdb.

Can be implement it by ourself?

**Comment by Giorgi** [comment]
@bnuzhouwei I can give it a try if there are enough [Sponsors](https://github.com/sponsors/Giorgi) for the project

**Comment by ulissescappato** [comment]
@bnuzhouwei, can we support the project together? I also need this feature. Thanks!

**Comment by Seddryck** [comment]
I also need it, will give it a try.

**Comment by Giorgi** [comment]
Thanks @Seddryck
