### ISSUE TITLE
DbParameter Support

### ISSUE THREAD

**Issue by bnuzhouwei** [Giorgi/DuckDB.NET#69]
ADO default use @param as paremnt, but duckdb use ?, can fill the gap with specified name of parameters?

**Comment by Giorgi** [comment]
@bnuzhouwei DuckDB itself doesn't support named parameters

**Comment by bnuzhouwei** [comment]
Could implement the parameters in the driver just like SQLite

**Comment by Giorgi** [comment]
SQLite has `sqlite3_bind_parameter_index` api that returns index of the parameter given it's name. There is no such API in DuckDB.

**Comment by bnuzhouwei** [comment]
The same issue exists in ClickHouse driver of ADO, while the jdbc driver works well among different databases.
 It's a pitty for .NET Ecosystem that hard to get consistent api of ADO among different databases.

**Comment by Giorgi** [comment]
You can open an issue for named parameters at the [DuckDB repository](https://github.com/duckdb/duckdb) If it gets added, I'll add support for it too.

**Comment by bnuzhouwei** [comment]
I have submit the issue: 
[Named parameters support](https://github.com/duckdb/duckdb/issues/5387)

**Comment by xllance** [comment]
You can use DynamicParameters Bag, which is basically a Dictictionary<string, object> like follows:
`
connectionn.Execute("INSERT INTO TestTable (Id,Name) VALUES ($1,$2)", new Dictionary<string, object> { { "$1", 1 }, { "$2", "some string" } });`

**Comment by Seddryck** [comment]
Sounds that named parameters are now supported by DuckDB: https://github.com/duckdb/duckdb/pull/5611

**Comment by Giorgi** [comment]
The necessary Api for named parameters isn't exposed in the C Api.

**Comment by Giorgi** [comment]
@Seddryck There is now a PR for this in DuckDB, once it gets merged and released it can be added to the library as well: [Add support for named parameters in prepared statements](https://github.com/duckdb/duckdb/pull/7113)

**Comment by Giorgi** [comment]
With the [release of DuckDB 0.9.0](https://duckdb.org/2023/09/26/announcing-duckdb-090.html), this is finally available (currently in the develop branch)
