### ISSUE TITLE
Allow multiple concurrent connections to the same DB

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#7]
The following code

```C#
using var duckDBConnection = new DuckDBConnection("Data Source=file.db");
  duckDBConnection.Open();

  using var conn2 = new DuckDBConnection("Data Source=file.db");
  conn2.Open();
```

raises an error.

According to the [c++ api docs](https://duckdb.org/docs/api/cpp), concurrent connections are allowed.

This one might be tricky to solve.

**Comment by travis-leith** [comment]
I am wondering about this code

```C#
var result = PlatformIndependentBindings.NativeMethods.DuckDBOpen(inMemory ? null : filename, out duckDBDatabase);
            if (result.IsSuccess())
            {
                result = PlatformIndependentBindings.NativeMethods.DuckDBConnect(duckDBDatabase, out NativeConnection);

                if (!result.IsSuccess())
                {
                    duckDBDatabase.Dispose();
                    throw new DuckDBException("DuckDBConnect failed", result);
                }
            }
            else
            {
                throw new DuckDBException("DuckDBOpen failed", result);
            }
```

Maybe `duckDBDatabase` should be an object the user creates once for an application and then multiple connections can be spawned from it.

**Comment by Giorgi** [comment]
I think you are right. The [C Api](https://duckdb.org/docs/api/c) says:

> With the duckdb_database handle, you can create one or many duckdb_connection using duckdb_connect(). While connections should be thread-safe, they will be locked during querying. It is therefore recommended that each thread uses its own connection.
