### ISSUE TITLE
Feature Request: NuGet package containing native libraries

### ISSUE THREAD

**Issue by nazar554** [Giorgi/DuckDB.NET#70]
Having a package with libraries for every platform would be nice. If referenced as a dependency the .NET runtime will find native libs automatically.
Just need to name them correctly  `runtimes/<platform rid>/native/duckdb.<dll/so/dylib>`, for example `runtimes/win-x86/native/duckdb.dll`

**Comment by arontsang** [comment]
@nazar554 Fixed in https://github.com/Giorgi/DuckDB.NET/pull/71

**Comment by Giorgi** [comment]
I'll close this issue once I publish the packages.

**Comment by Giorgi** [comment]
Packages published as https://www.nuget.org/packages/DuckDB.NET.Data.Full/ and https://www.nuget.org/packages/DuckDB.NET.Bindings.Full/
