### ISSUE TITLE
time with milliseconds is not handled properly

### ISSUE THREAD

**Issue by mikeTWC1984** [Giorgi/DuckDB.NET#74]
Steps to reproduce:

```csharp

        var duckDbCommand = connection.CreateCommand();
        duckDbCommand.CommandText = "select  now() as tme";
        var reader = duckDbCommand.ExecuteReader();
        reader.GetDateTime(0)
```
This will crash with below error

**"Valid values are between 0 and 999, inclusive. (Parameter 'millisecond')"**

now function returns time with milliseconds. If specifying time without milliseconds  (e.g. TIMESTAMP '1992-09-20 20:38:40' ) GetDateTime works correctly

**Comment by Giorgi** [comment]
Fixed in #93
