### ISSUE TITLE
How to property the connection string as java 

### ISSUE THREAD

**Issue by qmatrix123** [Giorgi/DuckDB.NET#78]
Properties ro_prop = new Properties();
ro_prop.setProperty("duckdb.read_only", "true");
Connection conn_ro = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database", ro_prop);

As java, I can pass configuration to connection.How can I do the same thing with the lib.

Thanks.

**Comment by qmatrix123** [comment]
I use these code to config the access_mode property, but it can not work.Please show me some hints.

```
using (var duckDBConnection = new DuckDB.NET.Data.DuckDBConnection(budiler.ConnectionString))
{

    duckDBConnection.Open();



    var command = duckDBConnection.CreateCommand();

    command.CommandText = "set access_mode=READ_ONLY;";
    var executeNonQuery = command.ExecuteNonQuery();



    command.CommandText = "SELECT current_setting('access_mode');";
    var executeScalar = command.ExecuteScalar();

    Thread.Sleep(1000 * 3);

    Console.WriteLine(executeScalar);
}
```

**Comment by Giorgi** [comment]
You cannot specify connection properties in the connection string yet but there is an open issue for that: #49 

You should be able to achieve it by using [Configure Api](https://github.com/Giorgi/DuckDB.NET/blob/main/DuckDB.NET/NativeMethods.cs#L33)

**Comment by Giorgi** [comment]
Your code also works for me with DuckDB 0.6.1:

![image](https://user-images.githubusercontent.com/580749/213141840-83020927-4f09-473a-afb5-9ef13ae05377.png)
