### ISSUE TITLE
DateTime is not supported for AppendValue method of Appender.

### ISSUE THREAD

**Issue by jeremylcarter** [Giorgi/DuckDB.NET#83]
https://github.com/Giorgi/DuckDB.NET/blob/5585dc529a9e7b92fb8478acf4508b4f3e2eec5c/DuckDB.NET.Data/DuckDBAppender.cs#L160

![image](https://user-images.githubusercontent.com/2087337/224460807-df1deea5-1f85-439d-a0d8-4640a79a8bca.png)

It appears its supported in the underlying method, but not in the `AppendValue` method overloads. I will add support and create a PR.

**Comment by Giorgi** [comment]
Implemented in 2cc5b99
