### ISSUE TITLE
Structs not supported?

### ISSUE THREAD

**Issue by EvanMachusak** [Giorgi/DuckDB.NET#87]
I am trying to use ADO.NET to query a table whose schema contains:

 column_name: code
    column_type: STRUCT(coding STRUCT(code VARCHAR, display VARCHAR, "system" VARCHAR)[], sof_codes VARCHAR[], "text" VARCHAR)

I've tried every reasonable variation of select statement that should work to extract columns out of that struct, e.g.
```
SELECT code.coding.code FROM ...
SELECT code.* FROM ...
```

The data types in question for these columns are 24 and 25, which are not supported.
This exception gets raised:

https://github.com/Giorgi/DuckDB.NET/blob/58a3bc90e5446ddfca998da5817ed115170fa202/DuckDB.NET.Data/DuckDBDataReader.cs#L122

These schemas come from parquet files, if that matters.

**Comment by Giorgi** [comment]
No, structs and lists aren't supported currently.

**Comment by EvanMachusak** [comment]
Would you entertain a PR for it?

**Comment by OneCyrus** [comment]
now that data chunks are implemented. any chance we get struct support?

**Comment by Giorgi** [comment]
* Allow setting naming convention for member names (camel case, pascal case, snake case).
* Allow custom naming convention for member names.
* Use expression trees to set properties
* Cache struct information for better performance

**Comment by Giorgi** [comment]
Structs are now working in the develop branch.

**Comment by Giorgi** [comment]
For now, I won't implement any naming customization.

**Comment by Giorgi** [comment]
Struct support is now live on NuGet

**Comment by EvanMachusak** [comment]
Thanks Giorgi.  This is really great.
