### ISSUE TITLE
Implement datareader methods GetValue, GetType and NextResult

### ISSUE THREAD

**Issue by travis-leith** [Giorgi/DuckDB.NET#9]
These are required for Dapper to do the automatic mapping from query to object.

**Comment by travis-leith** [comment]
This one was fairly simple. I have the changes on a branch on my fork called "reader".
However it assumes the multiple connections commits so lets get that wrapped up before I submit a PR for this.

**Comment by travis-leith** [comment]
https://github.com/travis-leith/DuckDB.NET/tree/reader

**Comment by Giorgi** [comment]
If you can send it in a PR that doesn't depend on multiple connections I will merge it.

**Comment by travis-leith** [comment]
@Giorgi 

Just FYI, I am currently integrating the latest changes in a project that previously used sqlite. Should take me a couple of hours. Once done I can confirm correctness based on my unit tests and if good you can release another nuget.

**Comment by Giorgi** [comment]
@travis-leith It will be interesting if you can share performance comparison between SQLite and DuckDb.

**Comment by travis-leith** [comment]
@Giorgi unfortunately that is not really practical right now, since I am prototyping a component of a bigger project, started using sqlite, realized it was not appropriate when I got to the point of ingesting large amounts of data and then decided to switch to DuckDB. So I don't have anything meaty to test yet.
But all my tests have now passed using the latest stuff here, so I think it is safe to release a new nuget.

**Comment by Giorgi** [comment]
@travis-leith New version published.
